Repository wecode-bootcamp-korea/43-1st-4iz-frontend, pull requests merged in 2023-03, with the labels that each got.

#5 [43기 이솜이] ADD : component 추가
  src/components/Button/Button.js
  src/components/Button/Button.scss
Labels: 완료

#2 [43기 장지아] ADD : Nav bar layout 구현
  public/images/nike.png
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/navData.js
Labels: 완료

#6 [43기 이솜이] ADD : Login page 구현
  public/images/nike.png
  public/images/sea.png
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: 완료

#7 [43기 이솜이] MODIFY : button tag에 className 추가
  src/components/Button/Button.js
Labels: 완료

#8 [43기 장지아] MODIFY : Nav 폰트 사이즈 충돌 문제 해결
  src/components/Nav/Nav.scss
Labels: 완료

#9 [43기 장지아] MODIFY : Footer 폰트 사이즈 충돌 문제 해결
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: 완료

#1 [43기 이솜이] ADD : Email verification layout 구현
  src/pages/Email/Email.js
  src/pages/Email/Email.scss
Labels: 완료

#10 [43기 이솜이] ADD : Signup page 구현
  src/pages/Signup/SIgnup.js
  src/pages/Signup/Signup.scss
Labels: 완료

#11 [43기 장지아] ADD : ProductList 레이아웃 구현
  public/data/productListData.json
  public/images/shoes1.png
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/ProductList/filterData.js
Labels: 완료

#13 [43기 장지아] ADD : Login 페이지 Button 컴포넌트 추가
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: 완료

#14 [43기 이솜이] MODIFY : Button component name 수정
  src/pages/Signup/SIgnup.js
Labels: 완료

#15 [43기 이솜이] ADD : Authentication page 파일/폴더 추가 및 router 연결
  src/Router.js
  src/pages/Authentication/Authentication.js
  src/pages/Authentication/Authentication.scss
Labels: 완료

#17 [43기 이솜이] ADD : Authentication Page 레이아웃 구현
  src/pages/Authentication/Authentication.js
  src/pages/Authentication/Authentication.scss
Labels: 완료

#18 [43기 장지아] MODIFY : ProductCard 컴포넌트 분리 및 ProductList 리팩토링
  src/Router.js
  src/components/ProductCard/ProductCard.js
  src/components/ProductCard/ProductCard.scss
  src/pages/Authentication/Authentication.js
  src/pages/Authentication/Authentication.scss
  src/pages/Email/Email.js
  src/pages/Email/Email.scss
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/ProductList/filterData.js
  src/pages/Signup/SIgnup.js
  src/pages/Signup/Signup.scss
Labels: Conflict 해결 요청, 멘토 리뷰 요청

#21 [43기 장지아] ADD : checkbox 스타일 mixin 추가
  src/styles/variables.scss
Labels: 완료

#20 [43기 장지아] ADD : Order 페이지 레이아웃 구현
  src/pages/Order/Order.js
  src/pages/Order/Order.scss
  src/pages/Signup/Signup.js
Labels: 완료

#24 [43기 이솜이] MODIFY : button component margin-top 삭제 및 hover style 적용
  src/components/Button/Button.scss
Labels: 완료

#19 [43기 이솜이] ADD : product detail Page 레이아웃 구현
  public/data/productData.json
  public/images/airforce_1.jpg
  public/images/airforce_2.jpg
  public/images/airforce_3.jpg
  public/images/airforce_4.jpg
  src/components/CartCard/CartCard.js
  src/components/CartCard/CartCard.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/styles/variables.scss
Labels: 멘토 리뷰 요청

#25 [43기 장지아] ADD : 로그인, 회원가입 통신 테스트 통과
  src/Router.js
  src/components/Nav/Nav.js
  src/pages/Account/Account.js
  src/pages/Account/Account.scss
  src/pages/Account/AccountList.js
Labels: 멘토 리뷰 요청, 완료

#28 [43기 장지아] ADD : darkgray variables 추가
  src/styles/variables.scss
Labels: 멘토 리뷰 요청

#26 [43기 장지아] MODIFY : ProductList mock data 반영
  public/data/productListData.json
  src/components/ProductCard/ProductCard.js
  src/components/ProductCard/ProductCard.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
Labels: 멘토 리뷰 요청

#29 [43기 이솜이] ADD : 배송옵션 유효성 검사 기능 추가
  src/Util/regex.js
  src/pages/Account/Account.js
  src/pages/Order/Order.js
  src/pages/Order/Order.scss
  src/styles/variables.scss
Labels: 멘토 리뷰 요청

#30 [43기 장지아] ProductList filter 쿼리스트링 테스트
  public/index.html
  src/components/Filter/Filter.js
  src/components/Filter/Filter.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
Labels: 멘토 리뷰 요청, 완료

#31 [43기 이솜이] product detail 통신 연결
  public/data/cartList.json
  public/data/productData.json
  src/pages/Account/Account.js
  src/pages/ProductDetail/ProductDetail.js
Labels: 추가 기능 구현 중

#33 [43기 이솜이] 최종 주문 상품 정보 및 배송옵션 데이터 통신 기능 구현
  src/Util/regex.js
  src/components/CartCard/CartCard.js
  src/pages/Cart/Cart.js
  src/pages/Order/Order.js
  src/pages/Order/Order.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
Labels: 완료

#34 [43기 장지아] main 페이지 스타일 완성
  public/images/4izLogo.png
  public/images/mainBgWhite.png
  public/images/mainShoeImg.png
  public/images/mainbg.png
  public/images/mainbg1.png
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: 멘토 리뷰 요청
